In [1]:
import pandas as pd
df=pd.read_csv('dataset/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
data=pd.read_csv('dataset/All_Pokemon.csv')
data.head()

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6

In [4]:
data.dtypes

Number                       int64
Name                        object
Type 1                      object
Type 2                      object
Abilities                   object
HP                           int64
Att                          int64
Def                          int64
Spa                          int64
Spd                          int64
Spe                          int64
BST                          int64
Mean                       float64
Standard Deviation         float64
Generation                 float64
Experience type             object
Experience to level 100      int64
Final Evolution            float64
Catch Rate                   int64
Legendary                  float64
Mega Evolution             float64
Alolan Form                float64
Galarian Form              float64
Against Normal             float64
Against Fire               float64
Against Water              float64
Against Electric           float64
Against Grass              float64
Against Ice                float64
Against Fighting           float64
Against Poison             float64
Against Ground             float64
Against Flying             float64
Against Psychic            float64
Against Bug                float64
Against Rock               float64
Against Ghost              float64
Against Dragon             float64
Against Dark               float64
Against Steel              float64
Against Fairy              float64
Height                     float64
Weight                     float64
BMI                        float64
dtype: object

In [5]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [6]:
#Data preprocessing

#null values - missing values 
data.isnull().any()

Number                     False
Name                       False
Type 1                     False
Type 2                      True
Abilities                  False
HP                         False
Att                        False
Def                        False
Spa                        False
Spd                        False
Spe                        False
BST                        False
Mean                       False
Standard Deviation         False
Generation                 False
Experience type            False
Experience to level 100    False
Final Evolution            False
Catch Rate                 False
Legendary                  False
Mega Evolution             False
Alolan Form                False
Galarian Form              False
Against Normal             False
Against Fire               False
Against Water              False
Against Electric           False
Against Grass              False
Against Ice                False
Against Fighting           False
Against Poison             False
Against Ground             False
Against Flying             False
Against Psychic            False
Against Bug                False
Against Rock               False
Against Ghost              False
Against Dragon             False
Against Dark               False
Against Steel              False
Against Fairy              False
Height                     False
Weight                     False
BMI                        False
dtype: bool

In [7]:
data.isnull().sum()

Number                       0
Name                         0
Type 1                       0
Type 2                     484
Abilities                    0
HP                           0
Att                          0
Def                          0
Spa                          0
Spd                          0
Spe                          0
BST                          0
Mean                         0
Standard Deviation           0
Generation                   0
Experience type              0
Experience to level 100      0
Final Evolution              0
Catch Rate                   0
Legendary                    0
Mega Evolution               0
Alolan Form                  0
Galarian Form                0
Against Normal               0
Against Fire                 0
Against Water                0
Against Electric             0
Against Grass                0
Against Ice                  0
Against Fighting             0
Against Poison               0
Against Ground               0
Against Flying               0
Against Psychic              0
Against Bug                  0
Against Rock                 0
Against Ghost                0
Against Dragon               0
Against Dark                 0
Against Steel                0
Against Fairy                0
Height                       0
Weight                       0
BMI                          0
dtype: int64

In [8]:
#drop null valus
#replace null values with something
data.head()

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6

In [9]:
len(data)

1032

In [12]:
#data=data.dropna()
#or
data.dropna(inplace=True)

In [13]:
data.isnull().sum()

Number                     0
Name                       0
Type 1                     0
Type 2                     0
Abilities                  0
HP                         0
Att                        0
Def                        0
Spa                        0
Spd                        0
Spe                        0
BST                        0
Mean                       0
Standard Deviation         0
Generation                 0
Experience type            0
Experience to level 100    0
Final Evolution            0
Catch Rate                 0
Legendary                  0
Mega Evolution             0
Alolan Form                0
Galarian Form              0
Against Normal             0
Against Fire               0
Against Water              0
Against Electric           0
Against Grass              0
Against Ice                0
Against Fighting           0
Against Poison             0
Against Ground             0
Against Flying             0
Against Psychic            0
Against Bug                0
Against Rock               0
Against Ghost              0
Against Dragon             0
Against Dark               0
Against Steel              0
Against Fairy              0
Height                     0
Weight                     0
BMI                        0
dtype: int64

In [14]:
len(data)

548

In [16]:
data=pd.read_csv('dataset/All_Pokemon.csv')
data

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49.0,49,65,65.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,NaN,63,80,80.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82.0,83,100,NaN,...,1.0,1.0,1.0,1.0,NaN,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100.0,123,122,120.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52.0,43,60,50.0,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145.0,130,65,110.0,...,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.2,800.0,165.3
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65.0,60,145,80.0,...,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1
1029,898,Calyrex,Psychic,Grass,['Unnerve'],100,80.0,80,80,80.0,...,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165.0,150,85,130.0,...,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85.0,80,165,100.0,...,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3

In [ ]:
#Data Imputation
!pip install scikit-learn
#command prompt - > pip install scikit-learn
#anaconda prompt -> conda install scikit-learn

In [17]:
data.isnull().sum()

Number                       0
Name                         0
Type 1                       0
Type 2                     484
Abilities                    0
HP                           0
Att                          1
Def                          0
Spa                          0
Spd                          1
Spe                          0
BST                          0
Mean                         0
Standard Deviation           0
Generation                   0
Experience type              0
Experience to level 100      0
Final Evolution              0
Catch Rate                   0
Legendary                    0
Mega Evolution               0
Alolan Form                  0
Galarian Form                0
Against Normal               0
Against Fire                 0
Against Water                0
Against Electric             0
Against Grass                0
Against Ice                  0
Against Fighting             0
Against Poison               0
Against Ground               0
Against Flying               0
Against Psychic              0
Against Bug                  0
Against Rock                 0
Against Ghost                0
Against Dragon               0
Against Dark                 1
Against Steel                0
Against Fairy                0
Height                       0
Weight                       0
BMI                          0
dtype: int64

In [21]:
from sklearn.impute import SimpleImputer
import numpy as np
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') #only number "most-frequent"

#category - most_frequent
#number - mean, median, constant (e.g 100, 10)

values=data[['Att','Spd','Against Dark']]
result=np.round(imputer.fit_transform(values),2)
data[['Att','Spd','Against Dark']]=result
data

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49.00,49,65,65.00,...,1.0,1.0,1.0,1.0,1.00,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,80.54,63,80,80.00,...,1.0,1.0,1.0,1.0,1.00,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82.00,83,100,72.11,...,1.0,1.0,1.0,1.0,1.07,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100.00,123,122,120.00,...,1.0,1.0,1.0,1.0,1.00,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52.00,43,60,50.00,...,0.5,2.0,1.0,1.0,1.00,0.5,0.5,0.6,8.5,23.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145.00,130,65,110.00,...,1.0,2.0,1.0,1.0,1.00,2.0,1.0,2.2,800.0,165.3
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65.00,60,145,80.00,...,0.5,1.0,2.0,1.0,2.00,1.0,1.0,2.0,44.5,11.1
1029,898,Calyrex,Psychic,Grass,['Unnerve'],100,80.00,80,80,80.00,...,4.0,1.0,2.0,1.0,2.00,1.0,1.0,1.1,7.7,6.4
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165.00,150,85,130.00,...,2.0,2.0,2.0,1.0,2.00,2.0,1.0,2.4,809.1,140.5
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85.00,80,165,100.00,...,1.0,1.0,4.0,1.0,4.00,1.0,1.0,2.4,53.6,9.3

In [27]:
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent') #only number "most-frequent"
vv=data['Type 2'].values.reshape(-1,1)
result=imputer.fit_transform(vv)
data['Type 2']=result
data.head()

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49.00,49,65,65.00,...,1.0,1.0,1.0,1.0,1.00,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,80.54,63,80,80.00,...,1.0,1.0,1.0,1.0,1.00,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82.00,83,100,72.11,...,1.0,1.0,1.0,1.0,1.07,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100.00,123,122,120.00,...,1.0,1.0,1.0,1.0,1.00,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,Flying,"['Blaze', 'Solar Power']",39,52.00,43,60,50.00,...,0.5,2.0,1.0,1.0,1.00,0.5,0.5,0.6,8.5,23.6

In [30]:
data['Type 2'].values.reshape(-1,1) #1,-1

array([['Poison'],
       ['Poison'],
       ['Poison'],
       ...,
       ['Grass'],
       ['Ice'],
       ['Ghost']], dtype=object)

In [31]:
from sklearn.impute import KNNImputer #Kth nearest neighbor #only number
imputer=KNNImputer(n_neighbors=5,weights="uniform")
vv=data[['Att','Spd','Against Dark']]
value=imputer.fit_transform(vv)
value

array([[ 49.  ,  65.  ,   1.  ],
       [ 80.54,  80.  ,   1.  ],
       [ 82.  ,  72.11,   1.07],
       ...,
       [ 80.  ,  80.  ,   2.  ],
       [165.  , 130.  ,   2.  ],
       [ 85.  , 100.  ,   4.  ]])

In [37]:
data['Type 2'].value_counts()

Flying      596
Psychic      42
Fairy        41
Ground       39
Poison       37
Steel        35
Fighting     31
Dragon       30
Grass        28
Ghost        27
Dark         26
Water        20
Ice          18
Fire         17
Rock         15
Electric     11
Normal       10
Bug           9
Name: Type 2, dtype: int64

In [38]:
pd.get_dummies(data,columns=['Type 2']) #One Hot Encoder

,Number,Name,Type 1,Abilities,HP,Att,Def,Spa,Spd,Spe,...,Type 2_Ghost,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,1,Bulbasaur,Grass,"['Chlorophyll', 'Overgrow']",45,49.00,49,65,65.00,45,...,0,0,0,0,0,1,0,0,0,0
1,2,Ivysaur,Grass,"['Chlorophyll', 'Overgrow']",60,80.54,63,80,80.00,60,...,0,0,0,0,0,1,0,0,0,0
2,3,Venusaur,Grass,"['Chlorophyll', 'Overgrow']",80,82.00,83,100,72.11,80,...,0,0,0,0,0,1,0,0,0,0
3,3,Mega Venusaur,Grass,['Thick Fat'],80,100.00,123,122,120.00,80,...,0,0,0,0,0,1,0,0,0,0
4,4,Charmander,Fire,"['Blaze', 'Solar Power']",39,52.00,43,60,50.00,65,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,896,Glastrier,Ice,['Chilling Neigh'],100,145.00,130,65,110.00,30,...,0,0,0,0,0,0,0,0,0,0
1028,897,Spectrier,Ghost,['Grim Neigh'],100,65.00,60,145,80.00,130,...,0,0,0,0,0,0,0,0,0,0
1029,898,Calyrex,Psychic,['Unnerve'],100,80.00,80,80,80.00,80,...,0,1,0,0,0,0,0,0,0,0
1030,898,Calyrex Ice Rider,Psychic,['As One'],100,165.00,150,85,130.00,50,...,0,0,0,1,0,0,0,0,0,0
1031,898,Calyrex Shadow Rider,Psychic,['As One'],100,85.00,80,165,100.00,150,...,1,0,0,0,0,0,0,0,0,0

In [43]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
value=ohe.fit_transform(data['Type 2'].values.reshape(-1,1)).toarray()
value

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
value=ohe.fit_transform(data['Type 1'].values.reshape(-1,1)).toarray()
value

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
!pip install keras

In [47]:
#Norminal categorical --> numeric  - one hot encoder
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
lbl.fit(data['Type 1'])
values=lbl.transform(data['Type 1'])
values

array([ 9,  9,  9, ..., 14, 14, 14])

In [48]:
data['Type 1'].value_counts()

Water       131
Normal      114
Grass        91
Bug          81
Psychic      77
Fire         64
Rock         59
Electric     59
Dark         46
Dragon       42
Fighting     42
Ground       41
Ghost        41
Poison       40
Ice          38
Steel        36
Fairy        22
Flying        8
Name: Type 1, dtype: int64

In [51]:
from sklearn.preprocessing import OrdinalEncoder
lbl=OrdinalEncoder()
values=lbl.fit_transform(data['Type 1'].values.reshape(-1,1))
values

array([[ 9.],
       [ 9.],
       [ 9.],
       ...,
       [14.],
       [14.],
       [14.]])