In [2]:
import pandas as pd
df=pd.read_csv('dataset/Sales_Data/alldf.csv')
df

,Unnamed: 0,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales Amount,Month,Day,Hour,City
0,0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001",23.90,April,19,8,Dallas
1,2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215",99.99,April,7,22,Boston
2,3,176560,Google Phone,1,600.00,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",600.00,April,12,14,Los Angeles
3,4,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",11.99,April,12,14,Los Angeles
4,5,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001",11.99,April,30,9,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...
185945,17656,295660,AAA Batteries (4-pack),2,2.99,2019-11-04 14:17:00,"574 4th St, Los Angeles, CA 90001",5.98,November,4,14,Los Angeles
185946,17657,295661,USB-C Charging Cable,1,11.95,2019-11-23 07:22:00,"359 1st St, Austin, TX 73301",11.95,November,23,7,Austin
185947,17658,295662,Lightning Charging Cable,1,14.95,2019-11-13 16:12:00,"900 10th St, Boston, MA 02215",14.95,November,13,16,Boston
185948,17659,295663,AAA Batteries (4-pack),1,2.99,2019-11-17 17:08:00,"592 Sunset St, Boston, MA 02215",2.99,November,17,17,Boston
185949,17660,295664,Google Phone,1,600.00,2019-11-17 16:13:00,"428 Jackson St, Boston, MA 02215",600.00,November,17,16,Boston

In [3]:
df['Sales Amount'].sum()

34492035.97

In [5]:
df['Product'].nunique()

19

In [9]:
month='November'
city='Boston'
product=['Google Phone','Lightning Charging Cable']

df_selection=df.query("Product==@product and Month==@month and City==@city")
df_selection

,Unnamed: 0,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales Amount,Month,Day,Hour,City
168423,53,278845,Lightning Charging Cable,1,14.95,2019-11-09 11:46:00,"497 6th St, Boston, MA 02215",14.95,November,9,11,Boston
168485,116,278906,Lightning Charging Cable,1,14.95,2019-11-04 14:51:00,"873 Hickory St, Boston, MA 02215",14.95,November,4,14,Boston
168534,166,278951,Lightning Charging Cable,1,14.95,2019-11-07 17:03:00,"401 13th St, Boston, MA 02215",14.95,November,7,17,Boston
168571,203,278987,Lightning Charging Cable,1,14.95,2019-11-05 21:38:00,"704 11th St, Boston, MA 02215",14.95,November,5,21,Boston
168589,221,279005,Lightning Charging Cable,1,14.95,2019-11-16 07:05:00,"222 12th St, Boston, MA 02215",14.95,November,16,7,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...
185769,17480,295488,Lightning Charging Cable,1,14.95,2019-11-16 07:09:00,"876 Dogwood St, Boston, MA 02215",14.95,November,16,7,Boston
185817,17528,295534,Google Phone,1,600.00,2019-11-06 19:21:00,"22 Pine St, Boston, MA 02215",600.00,November,6,19,Boston
185825,17536,295541,Lightning Charging Cable,1,14.95,2019-11-15 16:25:00,"774 Madison St, Boston, MA 02215",14.95,November,15,16,Boston
185947,17658,295662,Lightning Charging Cable,1,14.95,2019-11-13 16:12:00,"900 10th St, Boston, MA 02215",14.95,November,13,16,Boston
185949,17660,295664,Google Phone,1,600.00,2019-11-17 16:13:00,"428 Jackson St, Boston, MA 02215",600.00,November,17,16,Boston

In [11]:
df_selection.groupby('Product')['Sales Amount'].sum().sort_values(ascending=False)

Product
Google Phone                28800.00
Lightning Charging Cable     3842.15
Name: Sales Amount, dtype: float64

In [12]:
sales_by_month=df_selection.groupby('Month')['Sales Amount'].sum().sort_values(ascending=False)
sales_by_month

Month
November    32642.15
Name: Sales Amount, dtype: float64